# Generated by Django 6.0.5 on 2026-05-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Send money transfer', 'verbose_name_plural': 'Send money transfers'},
        ),
    ]
