# Generated by Django 6.0.5 on 2026-07-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_balance_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='recipient_wallet_address',
            field=models.CharField(blank=True, default='', max_length=42),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_wallet_address',
            field=models.CharField(blank=True, default='', max_length=42),
        ),
    ]
