# Generated by Django 6.0.5 on 2026-07-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transfer_wallet_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='escrow_release_tx_hash',
            field=models.CharField(blank=True, default='', max_length=66),
        ),
        migrations.AddField(
            model_name='transfer',
            name='escrow_status',
            field=models.CharField(default='locked', max_length=20),
        ),
        migrations.AddField(
            model_name='transfer',
            name='escrow_tx_hash',
            field=models.CharField(blank=True, default='', max_length=66),
        ),
        migrations.AddField(
            model_name='transfer',
            name='privacy_mode',
            field=models.BooleanField(default=True),
        ),
    ]
